### ISSUE TITLE
Context factory output doesn't match config model

### ISSUE THREAD

**Issue by nicolaskvh** [getgelato/gelato#18]
The context factory returns an object with a config property which doesn't match the config interface.

**Comment by nvandoorn** [comment]
Thanks for reporting this. It may also be worth adding a type annotation on what the factory returns (in this case it should return `Context`)

**Comment by nicolaskvh** [comment]
I fixed this but basically just by giving it the shape it wanted without actually implementing anything. Should I submit it as a separate PR? I was just quickly trying to get tests working again as this broke all of them which was making it diffic. I couldn't finish the other PR.ult to finish the other open PR. Could've removed the context object from where it was being used from within the rasp-gpio adapter but that seemed like poor form to me.
